export const currentSkills = [
    "JavaScript: ES6+",
    "Semantic and accessible HTML",
    "CSS BEM convention",
    "CSS Grid",
    "CSS Flex",
    "Markdown",
    "React",
    "React Router",
    "React Hooks",
    "Redux-Saga",
    "Redux (Toolkit)",
    "Immutability",
    "Local Storage",
    "Styled components",
    "Error handling",
    "Working with API (axios, fetch)",
    "Git",
    "Scrum",
    "NPM",
    "GitHub Pull Request & Review",
    "Trello",
    "Promises, Asyns/Await",
    "Responsive Web Design",
    "Teamwork",
];

export const nextSkills = [
    "Node.js",
    "Vue.js",
    "Next.js",
    "React Query",
    "SCSS",
    "REST API",
    "TypeScript",
    "Figma",
    "React Context",    
];